version: "3.8"
services:
  bitcoin-core:
    env_file:
    - .env
    image: ruimarinho/bitcoin-core:latest
    container_name: bitcoin-core
    command:
      - "-printtoconsole"
      - "-rpcallowip=0.0.0.0/0"
      - "-rpcbind=0.0.0.0"
      - "-rpcuser=naas"
      - "-rpcpassword=${BTC_PASSWORD}"
    ports:
      - "8332:8332"
      - "8333:8333"
    volumes:
      - ".bitcoin:/home/bitcoin/.bitcoin"
    networks:
      - naas_network

  openresty:
    env_file:
      - .env
    image: openresty/openresty:latest
    ports:
      - "80:80"
    volumes:
      - "./nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf"
    networks:
      - naas_network
      
  redis:
    env_file:
      - .env
    image: redis:latest
    command: redis-server --requirepass ${REDIS_PASSWORD}
    # ports:
    #   # - "6379:6379"
    networks:
      - naas_network

networks:
  naas_network:
    name: naas_network